name: Trigger ClearML Pipeline

on:
  push:
    # any branch named feature/<anything>
    branches: [main]

jobs:
  run-pipeline:
    name: Run FireWatch Pipeline
    runs-on: ubuntu-latest
    env:
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Trigger ClearML Pipeline
        run: |
          # if you want the pipeline controller script in your repo root:
          python pipeline.py
